# Generated by Django 4.1.2 on 2022-10-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0002_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
    ]
