# Generated by Django 4.1.2 on 2022-10-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0003_remove_account_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='full_name',
        ),
    ]
