# Generated by Django 4.1.2 on 2022-10-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0005_alter_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
