# Generated by Django 4.1.2 on 2022-10-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0006_employee_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
