# Generated by Django 4.1.2 on 2022-10-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0007_employee_is_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=100)),
                ('is_booked', models.BooleanField(default=False)),
                ('booked_by', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
