# Generated by Django 4.1.2 on 2022-10-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0008_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='slot',
        ),
        migrations.AddField(
            model_name='slot',
            name='slot_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
