# Generated by Django 4.1.2 on 2022-10-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0009_remove_slot_slot_slot_slot_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slot_row',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot',
            name='booked_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
