# Generated by Django 4.1.1 on 2022-10-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0011_employee_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='imgUpload')),
            ],
        ),
        migrations.AddField(
            model_name='slot',
            name='user_mail',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
