# Generated by Django 4.1.2 on 2022-10-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0012_imgupload_slot_user_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='slot_row',
            field=models.CharField(max_length=100),
        ),
    ]
